
<div class="container">
<h2 class="text-center text-uppercase mb-0" style="color:white; padding-bottom:30px;">Edit</h2>
  <div class="row">
    <div class="col-sm">     
      </div>
      <div class="col-sm">
        <form action="" method="post" enctype="multipart/form-data">
          <div class="form-group">
            <label>ชื่อกิจกรรม</label>
            <input type="text" name="name" class="form-control" id="event_name" placeholder="Event name" value="<?php echo $event->name?>" required >
          </div>
          <div class="form-group">
            <label>วันที่</label>
            <input type="date" name="date" class="form-control" id="event_date" min="2018-01-01" max="2019-12-31" value="<?php echo $event->date?>" required>
          </div>
          <div class="form-group">
            <label>รายละเอียด</label>
            <textarea name="detail" class="form-control" id="event_detail" rows="3" placeholder="Event Detail" required> <?php echo $event->detail?></textarea>
          </div> 
          
          <div class="form-group">
            <label>ภาพกิจกรรม</label>
            <input type="file" name="picture" class="form-control" id="event_picture">
          </div> 
          

          <?php if($event->picture!=''){?>
            <div class="form-group text-center">  
                    <img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/'.$event->picture; ?>">
            </div>
        <?php }?>
          
          <button type="submit" class="btn btn-info">Submit</button>
          
          <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
          
        </form>
      </div>
      <div class="col-sm">     
        </div>
      </div>
    </div>