<div class="container" id="about" style="">
<ul class="myname" style="">
    <li class="myname-item">Name : Tin Inpankaew</li>
    <li class="myname-item">No : 590610618</li>
    <li class="myname-item">Email : oat22@windowslive.com</li>
    <li class="myname-item">Tell : 089-7558430</li>
    <li class="myname-item"><img style="width:100px; height:100px" src="<?php echo $this->url->getBaseUri().'public/img/mypic.jpg'; ?>"></li>

</ul>

<div class="row" style="padding: 10px;"></div>
<a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
</div>